version: '3.9'
services:
  langfuse:
    image: 'langfuse/langfuse:2'
    container_name: langfuse
    restart: unless-stopped
    networks:
      - langfuse-network
    ports:
      - '3010:3010'
    environment:
      - PORT=3010
      - HOSTNAME=0.0.0.0
      - NEXTAUTH_URL=${SERVICE_FQDN_LANGFUSE_3010}
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - DIRECT_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}
      - SALT=${SERVICE_PASSWORD_SALT}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - AUTH_DISABLE_SIGNUP=false
      - TELEMETRY_ENABLED=false
      - LANGFUSE_ENABLE_EXPERIMENTAL_FEATURES=false
      - LANGFUSE_INIT_USER_NAME=Admin
      - LANGFUSE_INIT_USER_EMAIL=admin@example.com
      - LANGFUSE_INIT_USER_PASSWORD=${SERVICE_PASSWORD_LANGFUSE}
      - LANGFUSE_INIT_ORG_ID=my-org
      - LANGFUSE_INIT_ORG_NAME=My Org
      - LANGFUSE_INIT_PROJECT_ID=my-project
      - LANGFUSE_INIT_PROJECT_NAME=My Project
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.langfuse.rule=Host(`langfuse.111122112.com`)"
      - "traefik.http.services.langfuse.loadbalancer.server.port=3010"
      - "traefik.http.routers.langfuse.entrypoints=web,websecure"
      - "traefik.http.routers.langfuse.tls=true"
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:3010/api/public/health || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 3
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    image: 'postgres:16-alpine'
    container_name: langfuse-postgres
    restart: unless-stopped
    networks:
      - langfuse-network
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 15

volumes:
  pg-data:
    name: langfuse-pg-data

networks:
  langfuse-network:
    name: langfuse-network
    driver: bridge 